### ISSUE TITLE
[BUG] White noise when resampling 48K model to 96K in DAW

### ISSUE THREAD

**Issue by 2-dor** [sdatkinson/NeuralAmpModelerPlugin#398] opened 2023-12-04 19:27 UTC
Noticeable increase in apparent noise floor when using a 48k .nam model in a 96k project.

To reproduce:

- Launch DAW (used Reaper 7.06 in my case) and create 96K project
- Add a NAM plugin instance to a track, arm for recording
- Unplug any instrument cable going to the audio interface; lower all input volume sliders to minimum
- Load a .nam model trained as usual at 48K (don't load any IR after it)
- Notice the perceived noise volume (higher)
- Save the project & close the DAW
- Change the interface sample rate to 48K and relaunch the DAW / project
- Notice the perceived noise volume (lower than when upsampling to 96K)

**Comment by sdatkinson** [comment] 2023-12-05 03:54
I'm seeing this too.

Looping a DI that's just my guitar with volume knob all the way off, and a super-gainy model (expecting 48k) and the noise gate disabled, I get these integrated LUFS:

44.1 kHz: -44.0 LUFS
48 kHz:  -44.0 LUFS
88.2 kHz: -43.7 LUFS
96 kHz: -40.5 LUFS

Interesting that it really takes off with 96k with +3.5 dB.

I also don't see any difference when playing. Looping a DI with some strumming, all 4 sample rates converge to -17.6 LUFS. That's kind of interesting.

Out of curiosity, I benchmarked it against Tonocracy's NAM player running the same model. Theirs also sees the noise floor go up, but less (only +0.7 dB).

With a 20 kHz LPF like this...

<img width="576" alt="image" src="https://github.com/sdatkinson/NeuralAmpModelerPlugin/assets/12240186/73cdb1f0-802f-40ad-993d-2da01a63d239">

...the difference disappears.

So it seems to me that the culprit is how the highest-frequency signals are being handled by the resampling algorithm.

There are a few options:
1. Leave it alone and allow the user to do high-frequency treatment as they'd prefer (maximum flexibility, more user error)
2. Add that LPF into the code (it "just works" but more modification of the signal than what a "NAM purist" might want? Technically we're already resampling, so that's out the window?)
3. Perhaps the resampler can be tuned? I looked at the source code for the iPlug2 component I'm using but I don't see the parameters exposed in a way that suggests they were meant to be played with? (No initialization arguments or public methods). cc @olilarkin, lmk if I'm missing something here?  e.g. what's up with the magic number [`A=4`](https://github.com/iPlug2/iPlug2/blob/3f239d7c3060577e4088a2ce07d0a3e1dc185872/IPlug/Extras/LanczosResampler.h#L73C10-L73C10)?

**Comment by sdatkinson** [comment] 2023-12-05 04:10
A few other observations:
* This shouldn't affect the noise gate--the resampling only happens around the NAM; the rest of the DSP is done in the external sample rate.
* Something like the [Bertom Denoiser](https://www.bertomaudio.com/denoiser-classic.html), cutting highs, also makes things work fine...

Another thought: I can already imagine having to answer this question again and again. I'm not very keen on option (1) in my comment above. I certainly could do something like a first-order LPF at the Nyquist before feeding the signal into the resampler (only on the resampling path). Anything to make this less noticeable would probably be good.

---

I'm also wondering whether I should consider this a must-fix for this release or if it'd be okay to get it out there and patch it in the next one if I can get it tuned up.  My bet is that the majority of users will benefit from this because they're using 44.1. For them, this isn't an issue.  @2-dor, feel free to weigh in.

**Comment by 2-dor** [comment] 2023-12-05 05:33
> A few other observations:
> 
> * This shouldn't affect the noise gate--the resampling only happens around the NAM; the rest of the DSP is done in the external sample rate.
> * Something like the [Bertom Denoiser](https://www.bertomaudio.com/denoiser-classic.html), cutting highs, also makes things work fine...
> 
> Another thought: I can already imagine having to answer this question again and again. I'm not very keen on option (1) in my comment above. I certainly could do something like a first-order LPF at the Nyquist before feeding the signal into the resampler (only on the resampling path). Anything to make this less noticeable would probably be good.
> 
> I'm also wondering whether I should consider this a must-fix for this release or if it'd be okay to get it out there and patch it in the next one if I can get it tuned up. My bet is that the majority of users will benefit from this because they're using 44.1. For them, this isn't an issue. @2-dor, feel free to weigh in.

I think getting it out is priority so no biggie.

**Comment by olilarkin** [comment] 2023-12-05 07:52
There may well be a problem with the resampler when going from 96 to 48,
will have to test it in isolation.

**Comment by sdatkinson** [comment] 2023-12-05 16:48
Looking into it a little more, I have the sense that it would be appropriate for the choice of `A` to depend on what sample rates the Lanczos sampler is resampling between. However, I'm not sure of the details yet.

**Comment by olilarkin** [comment] 2023-12-05 20:27
I did a test with a sine sweep and i don't see any problems with the noise floor...

https://github.com/sdatkinson/NeuralAmpModelerPlugin/assets/655662/52871881-3ad9-4729-84ef-81367f004f4e

you can do the same with IPlugEffect...
```
#pragma once

#include "IPlug_include_in_plug_hdr.h"
#include "NonIntegerResampler.h"

const int kNumPresets = 1;

enum EParams
{
  kGain = 0,
  kNumParams
};

using namespace iplug;

class IPlugEffect final : public Plugin
{
public:
  IPlugEffect(const InstanceInfo& info);
  void ProcessBlock(sample** inputs, sample** outputs, int nFrames) override;
  void OnReset() override;
  NonIntegerResampler<> mNonIntegerResampler;
};
```

```
#include "IPlugEffect.h"
#include "IPlug_include_in_plug_src.h"

IPlugEffect::IPlugEffect(const InstanceInfo& info)
: Plugin(info, MakeConfig(kNumParams, kNumPresets))
, mNonIntegerResampler(48000, ESRCMode::kLancsoz)
{
  GetParam(kGain)->InitDouble("Gain", 0., 0., 100.0, 0.01, "%");
}

void IPlugEffect::OnReset()
{
  mNonIntegerResampler.Reset(GetSampleRate(), GetBlockSize());
}

void IPlugEffect::ProcessBlock(sample** inputs, sample** outputs, int nFrames)
{
  const double gain = GetParam(kGain)->Value() / 100.;
  const int nChans = NOutChansConnected();
  
  mNonIntegerResampler.ProcessBlock(inputs, outputs, nFrames,
  [nChans, gain](sample** inputs, sample** outputs, int nFrames){
    for (int s = 0; s < nFrames; s++) {
      for (int c = 0; c < nChans; c++) {
        outputs[c][s] = inputs[c][s] * gain;
      }
    }
  });

}
```

**Comment by olilarkin** [comment] 2023-12-06 17:47
could someone share a .nam and .ir that where i can easily reproduce the problem? I just tried it with a guitar here and i am not noticing much of a difference in the volume of the noise when i switch the host samplerate between 48 and 96k

**Closed** 2023-12-07 04:16 UTC
Labels: bug, priority:high, release-candidate

**Comment by olilarkin** [comment] 2023-12-10 15:05
I think setting A=12 is a big improvement for 44.1khz -> 48khz as well as 96khz->48khz. I've reworked the iPlug2 resampling classes to default to this value. I've also renamed the class... https://github.com/iPlug2/iPlug2/commit/4bfc3e15d67f0c7c930aab71d1bf0e551362a1c4

@sdatkinson if you define IPLUG_SIMDE you can get some extra performance too since i think you were using the scalar version before
