### ISSUE TITLE
[BUG] V0.7 GUI not displaying properly in Reaper

### ISSUE THREAD

**Issue by YoMnkn** [sdatkinson/NeuralAmpModelerPlugin#125] opened 2023-03-18 17:40 UTC
Hi! Newbie here, excuse my english, please.

I've tried NAM and sounds great. Problem is that V0.7 GUI doesn't display properly in Reaper 6.73. Neither does the standalone version. I'm on Win10 64bits SP1. I've reinstalled it and no luck. I attach a screen capture of the bug. Also, the profile and IR names that are loaded into the plugin don't show.

Thanks for all the work you are doing, guys!

![NAM 0 7 GUI REAPER BUG](https://user-images.githubusercontent.com/128249791/226123671-894ef82c-54d5-4ead-b4b6-d44432fbe9c7.png)

**Comment by sdatkinson** [comment] 2023-03-19 18:28
When was SP1 released? Trying to get a gauge of how far from current your OS is.

Do other plugins from [iPlug2's demos](https://github.com/iPlug2/iPlug2.github.io/releases) (e.g. IPlugEffect, which is fairly minimal) render correctly?

**Comment by jan-kowalski** [comment] 2023-03-19 19:54
Similar bug on Windows7 64bit. Interface GUI freeze but plugin works.

**Comment by sdatkinson** [comment] 2023-03-19 20:25
@jan-kowalski 

According to [iPlug2's documentation](https://github.com/iPlug2/iPlug2/blob/master/README.md),

> Windows 8, macOS 10.11, and iOS 14 are the official minimum target platforms

So I'm afraid this plugin may not be able to support your OS.

**Comment by gandalfthewhite19890404** [comment] 2023-03-20 08:57
Reaper 6.75, Win7 x64 - All is OK
![image](https://user-images.githubusercontent.com/24764335/226291727-4264a57d-6fcc-456c-a6c5-a9ae00c97725.png)

**Comment by YoMnkn** [comment] 2023-03-20 13:31
> When was SP1 released? Trying to get a gauge of how far from current your OS is.
> 
> Do other plugins from [iPlug2's demos](https://github.com/iPlug2/iPlug2.github.io/releases) (e.g. IPlugEffect, which is fairly minimal) render correctly?

Hi,

Win 10 SP1 was released on 2016, I think.

I've installed IPlugEffect (WIN_VST3_IPlugEffect_SKIA.zip) and it crashes Reaper.

**Comment by sdatkinson** [comment] 2023-08-09 04:17
Coming back around to this.

Appreciate you having a go with IPlugEffect. If you're not able to get that working, then I suspect that there's something at the iPlug2 level that's the root cause.

Based on that info, I'm going to close this as out of scope; if you're able to get IPlugEffect running, then we can re-open and look into what changed between the two perhaps. But getting IPlugEffect would definitely be the best first step to tackle.

**Closed by sdatkinson** 2023-08-09 04:17 UTC
Labels: bug
