### ISSUE TITLE
[BUG] NAM VST is crashing Reaper

### ISSUE THREAD

**Issue by SimonBaughen** [sdatkinson/NeuralAmpModelerPlugin#86] opened 2023-02-28 23:00 UTC
I have downloaded the installer for the vst. I have reaper on a windows 10 laptop. The vst appears in the reaper fx list. When I click to add it there follows a message that reaper has encountered a problem and has had to close. Reaper then closes.

**Comment by sdatkinson** [comment] 2023-03-03 02:04
What version of the plugin are you using?

**Comment by SimonBaughen** [comment] 2023-03-09 18:29
I am using 0.6.2.

**Comment by sdatkinson** [comment] 2023-03-10 03:14
0.7.0 was released recently and had some stability fixes. Mind updating and seeing if that helps?

**Comment by SimonBaughen** [comment] 2023-03-10 08:21
I'll give that a go and get back to you.

**Comment by SimonBaughen** [comment] 2023-03-11 11:28
Still crashing.

Log Name:      Application
Source:        Application Error
Date:          11/03/2023 11:21:06
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      User-PC
Description:
Faulting application name: reaper.exe, version: 6.5.7.0, time stamp: 0x6276d867
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x0000000000000000
Faulting process id: 0x934
Faulting application start time: 0x01d9540b7b06f53f
Faulting application path: C:\Program Files\REAPER (x64)\reaper.exe
Faulting module path: unknown
Report Id: d07dd1e1-bffe-11ed-b21f-d48564c3ed9b
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Level>2</Level>
    <Task>100</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2023-03-11T11:21:06.000000000Z" />
    <EventRecordID>265539</EventRecordID>
    <Channel>Application</Channel>
    <Computer>User-PC</Computer>
    <Security />
  </System>
  <EventData>
    <Data>reaper.exe</Data>
    <Data>6.5.7.0</Data>
    <Data>6276d867</Data>
    <Data>unknown</Data>
    <Data>0.0.0.0</Data>
    <Data>00000000</Data>
    <Data>c0000005</Data>
    <Data>0000000000000000</Data>
    <Data>934</Data>
    <Data>01d9540b7b06f53f</Data>
    <Data>C:\Program Files\REAPER (x64)\reaper.exe</Data>
    <Data>unknown</Data>
    <Data>d07dd1e1-bffe-11ed-b21f-d48564c3ed9b</Data>
  </EventData>
</Event>

Could you let me know what I have to download? Is it just the vst, or
is it also the source codes zip?

Thanks,

Simon

**Comment by sdatkinson** [comment] 2024-02-18 21:10
Closing this since the version that was involved is long past, there've been lots of bug fixes, and this doesn't have enough info to reproduce.

f you're still having trouble with the latest version, open a new Issue and include a crash dump as well as the other requested info.

**Closed by sdatkinson** 2024-02-18 21:10 UTC
Labels: bug

**Comment by SimonBaughen** [comment] 2024-02-18 22:09
Goodness, this is a blast from the past.

Had to get a new computer. NAM works fine on Reaper.

Keep up the good work,

Simon
