### ISSUE TITLE
[BUG] Standalone: Stereo inputs are confusing; Cannot set left input to Input 1 on a 2-input interface

### ISSUE THREAD

**Issue by KingKolya** [sdatkinson/NeuralAmpModelerPlugin#117] opened 2023-03-13 07:33 UTC
**Description**
when using ASIO driver the app can only use input 1 from my interface, setting input 1 and/or 2 to anything higher than 1 has no effect, preventing me from using my interfaces second input as a line in for the app.

**To Reproduce**
1. Go to 'file'
2. Click on 'preferences'
3. Set input and output device to 'Studio USB ASIO Driver'
4. Change Input 1 and/or 2 to 2

**Expected behavior**
use second interface input as line in, instead of first input

**Desktop**
 - OS windows 10
 - Plugin version 0.7
 - Standalone
 - Audio interface Presonus studio 24c
 
**Additional**
the app allows you to set 2 inputs, but only uses one, and won't allow you to set one of them to none.
plugging guitar into input 1 works fine when using the app in standalone mode, but isn't ideal since I normally have my mic in input 1 and permanently swapping would be tedious.

**Comment by seve54** [comment] 2023-03-15 13:26
I confirm error windows 11 input Asio Neural Amp Modeler standalone v.0.7

**Comment by seve54** [comment] 2023-03-15 15:24
> I confirm error windows 11 input Asio Neural Amp Modeler standalone v.0.7

![Senza titoloDDD](https://user-images.githubusercontent.com/77013086/225357690-07ab3394-9969-40ef-852a-5596360cc767.jpg)

**Comment by sdatkinson** [comment] 2023-03-19 18:25
Yep, good call.

I suspect that the root cause may be in iPlug2. I'll have to do some digging on it.

@seve54, I believe your issue is a different one from the OP.

**Comment by AndiOnGit** [comment] 2023-03-24 15:32
Maybe the 2-2 option is needed here:

#define PLUG_CHANNEL_IO "1-1 1-2 **2-2**"

**Comment by seve54** [comment] 2023-03-24 17:34
even switching inputs and outputs does not work standalone

**Comment by sdatkinson** [comment] 2023-05-01 04:36
This should be fixed with #166 and will be available in v0.7.3.

**Closed by sdatkinson** 2023-05-01 04:36 UTC
Labels: bug
