### ISSUE TITLE
Work in Pro Tools 2021?

### ISSUE THREAD

**Issue by PontoZero23** [sdatkinson/NeuralAmpModelerPlugin#384] opened 2023-10-31 12:55 UTC
Hello! I would like to know how I can make it work in Pro Tool 2021, because I installed it and it didn't recognize it, I tried to use it through StudioRack Wave and I wasn't successful either, any help if possible?!

**Comment by sdatkinson** [comment] 2023-12-14 04:24
In order to use this plugin in Pro Tools, you either need to build it as an AAX (#78 ), or you can open it inside a plugin container like [Blue Cat PatchWork](https://www.bluecataudio.com/Products/Product_PatchWork/).

I believe that either PatchWork should work (if it doesn't for you, I need more information to understand what to do) or if you're waiting for an AAX then this is a duplicate of #78, in which I'll close this as a duplicate--keep an eye on that Issue for news 👍🏻

**Closed by sdatkinson** 2023-12-14 04:24 UTC
Labels: enhancement, unread, priority:low
