### ISSUE TITLE
[FEATURE] AUv3 support

### ISSUE THREAD

**Issue by dbajpeyi** [sdatkinson/NeuralAmpModelerPlugin#363] opened 2023-08-17 09:26 UTC
**Is your feature request related to a problem? Please describe.**
It'd be amazing to be able to use this plugin as an iPad application. 

**Describe the solution you'd like**
A release targeting AUv3 so that I can load it into host apps like Drambo or Garageband. 

**Describe alternatives you've considered**
I've considered using BiasFX 2 but it doesn't support AUv3. There are some other apps too, but they don't compete with this feature because NAM works with machine learning, and the output is much nicer.

**Additional context**
I'd be happy to support adding this feature to the code as well, however I'd need some help understanding the architecture and also with building the code.

**Comment by sdatkinson** [comment] 2023-08-20 22:26
It should be possible to build from source--I just did so today myself out of curiosity on this.

A pre-built release distributed on the app store is a bit of a different matter. The issues there are mainly general and not really specific to NAM's code.

In the meantime, I'm going to close this as a duplicate of #261. We can continue to track this there.

**Closed by sdatkinson** 2023-08-20 22:26 UTC
Labels: enhancement, unread, priority:low

**Comment by dbajpeyi** [comment] 2023-08-24 11:06
Thanks, I will try this out today 😄
