### ISSUE TITLE
[FEATURE] IR and model path variables acting weird

### ISSUE THREAD

**Issue by 2-dor** [sdatkinson/NeuralAmpModelerPlugin#77] opened 2023-02-27 07:34 UTC
Using NAM 0.5.0:

- I successfully select an IR in the plugin & play with it
- I want another IR, when I click on the IR section the plugin remembers the directory I last used - all good
- I then want another .nam model and select one using the model directory section
- If I want yet another IR and click on the IR directory section, the plugin takes me to the folder from where my .nam model was instead of recalling the IR folder I last visited
- same thing happens the other way around; if I selected an IR and want to load a new .nam model, the plugin takes me to the IR directory

**Comment by sdatkinson** [comment] 2023-02-28 05:21
Looks like a duplicate of #62, so closing.  Feel free to re-open w/ more info if you think it's different.

**Closed by sdatkinson** 2023-02-28 05:21 UTC
Labels: enhancement, unread
