### ISSUE TITLE
No sound when loading an old 0.62 proyect in 0.7 NAM [BUG]

### ISSUE THREAD

**Issue by DarkSkar** [sdatkinson/NeuralAmpModelerPlugin#80] opened 2023-02-27 15:15 UTC
**the bug**
When I load and old proyect from 0.6.2 NAM version with the new 0.7 NAM installed now it opens in a wierd way and doesn't sound
In the input and output I see "-nan dB"

**To Reproduce**
Opening and old proyect

**Expected behavior**
I expected to open the old proyect without problems

**Screenshots**
[https://i.postimg.cc/YCZG0ygB/imagen.png](url)

**Desktop (please complete the following information):**
 - OS WIN 11
 - Plugin version  0.7
 - VST3 x64
 - DAW: Reaper 4.75

**Additional context**
I think this only happens with old proyects from old version,
 because I have created a new proyect and it seens to be working well (by now) with new proyects.

**Comment by sdatkinson** [comment] 2023-02-28 05:27
Right. This happens because there are different parameters in 0.7.0, so it doesn't line up when it loads in.

Is it an acceptable workaround to you to use new instances of the plugin instead of loading the old signal chains?

**Comment by sdatkinson** [comment] 2023-02-28 05:29
Going to close this and have this thread continue on #81, which I believe has the same root cause.

**Closed by sdatkinson** 2023-02-28 05:29 UTC
Labels: bug
