### ISSUE TITLE
[FEATURE] Next/ Previous buttons for amp captures

### ISSUE THREAD

**Issue by KelinLovell** [sdatkinson/NeuralAmpModelerPlugin#138] opened 2023-03-22 20:56 UTC
A simple forward and backwards option to select new amps instead of opening a folder every time. Or a small screen or "window" into the selected folder that allows to see other amp captures without opening a new window. Kind of like the STL version of Ignite's NadIR where contents of the selected IR folder show up on the plugin. Hopefully that makes sense! And sorry if this is a double post. I didn't see this when I looked around quickly, I did see a similar feature request for IR's though.

**Comment by sdatkinson** [comment] 2023-03-26 17:36
Closing as duplicate of #63. Go ahead & give that a +1 & we'll track there.

**Closed by sdatkinson** 2023-03-26 17:36 UTC
Labels: enhancement, unread
