### ISSUE TITLE
[BUG] I got this error while training ( Strep 3) : Mismatched shapes (3295456, 1) versus (3247456, 1)   . I guess when I did Freeze/Stereo in Reaper the shape changed comparing to the original v1_1_1.wav !!

### ISSUE THREAD

**Issue by Waitforthericochet** [sdatkinson/NeuralAmpModelerPlugin#173] opened 2023-04-06 22:26 UTC
**Thanks for taking the time to write a bug report!** Use the following prompts to help you describe what's going on.  The more info you provide, the easier it'll be to understand how to fix it for you without having to come back and ask you questions.

**Describe the bug**

**To Reproduce**

**Expected behavior**
I got this error while training ( Strep 3): Mismatched shapes (3295456, 1) versus (3247456, 1). I guess when I did Freeze/Stereo in Reaper the shape changed compared to the original v1_1_1.wav !!

**Screenshots**

**Desktop (please complete the following information):**
 - OS [e.g. Windows 10, macOS 10.15]
 - Plugin version [e.g. 0.6.1]
 - Standalone, VST3, or AU
 - DAW (Reaper)

**Additional context**
![error shapes](https://user-images.githubusercontent.com/128655521/230504613-e7a133ee-a2ce-4558-8b0b-17c2652499f1.jpg)
![error shapes](https://user-images.githubusercontent.com/128655521/230504654-bdc38dae-84e9-4b6a-8ca4-b260814e86cb.jpg)

**Comment by sdatkinson** [comment] 2023-04-09 05:22
This is an Issue not with the plugin, but the trainer, which lives at [neural-amp-modeler](https://github.com/sdatkinson/neural-amp-modeler), so I'm going to close it here.

The issue is that your input & output files aren't the same lengths as each other. (Also, your input file isn't the right length either--the file you downloaded is 2:59 long, or 8,592,000 samples long. Neither of your files are this long--they're over twice as short--about 1 minute 7 seconds long and 1 minute 8 seconds long...and change.)

**Closed by sdatkinson** 2023-04-09 05:22 UTC
Labels: bug, unread

**Comment by Waitforthericochet** [comment] 2023-04-09 15:13
Thank you for your answer. Yes, I did fix the issue ! Thank you very much
😊  for your help and support 🙏
