### ISSUE TITLE
[BUG] Input settings for NAM v0.7.0 on MacOS

### ISSUE THREAD

**Issue by jonatanmv** [sdatkinson/NeuralAmpModelerPlugin#144] opened 2023-03-26 17:24 UTC
**Thanks for taking the time to develop this open software !!**
I would like to report a bug found after installation and testing it...

**Bug description**
At least when using a Focusrite audio interface, the input used is always *input 1* whatever settings for *Input 1(L) and Input 2(R).

<img width="327" alt="Screenshot 2023-03-26 at 19 23 16" src="https://user-images.githubusercontent.com/2971622/227793020-5cbad305-56fa-4ee1-bc8a-261433df3e9b.png">

**To Reproduce**
1. Go to 'Preferences'
2. Click on 'Input 1(L)'
3. Scroll down to '2' (i.e select input 2 of interface)

**Expected behavior**

**Desktop (please complete the following information):**
 - OS macOS 11.7.4
 - Plugin version 0.7.0
 - Standalone (other not tested yet)

** Thanks !!**

**Comment by robiRagan** [comment] 2023-03-26 17:54
I have the same experience on a Behringer U-Phoria UMC404HD. 

No matter what the Settings in NAM display it is the signal from the mic I have in channel 1 on the interface that is actually heard by NAM. All other guitar sim stand alone software works correctly. 

iMac 2017 4.2 GHz Quad-Core Intel Core i7
MacOS 13.2.1

**Comment by sdatkinson** [comment] 2023-03-26 17:57
Appears to be a duplicate of #117. We'll continue tracking there.

Thanks!

**Closed by sdatkinson** 2023-03-26 17:57 UTC
Labels: bug, unread
