### ISSUE TITLE
[FEATURE] Stereo option to save CPU 

### ISSUE THREAD

**Issue by jimc4893** [sdatkinson/NeuralAmpModelerPlugin#190] opened 2023-04-13 11:39 UTC
Most amp modelers have a stereo option so you can bus two mono guitar tracks into it. This would be fantastic.

**Comment by damiangr** [comment] 2023-04-14 20:43
I'm strongly against it. Most amp modelers do not process amp in stero. You will double CPU utilisation in that case when you will use mono signal.

**Comment by jimc4893** [comment] 2023-04-14 21:07
It at least makes it easier when mixing, who doesn't double track everything nowadays?

**Comment by damiangr** [comment] 2023-04-15 08:10
> It at least makes it easier when mixing, who doesn't double track everything nowadays?

How it makes it easier.? Not every one pan double tracked guitars 100% L and R. It will only complicate things that you can easly do with another track in DAW if you need it.

With sterteo NAM i will have to use another Channel Mixing plugin  if i wan to have less narrowed image.
Nobody record doubled track to L or R. Most of users will record just another mono track. 

I thing overcomplicate things is bad idea. You can alwas recod Two tracks put nam on both and route to one stereo guitar bus. 
SImple and effective. 

If I want only one guitar track NAM will use twice CPU powet to process mono wave . This makes no sense to me. 

But maybe you can elaborate how it makes mixing better with stereo version.

**Comment by jimc4893** [comment] 2023-04-15 08:51
A stereo option is default in many top amp sims, and works to be able to have double tracked guitars and edit their tone without clicking between two tracks and copy and pasting the instance after each change. 

The advantage of this tool is to have amp capture modelling in a plugin, so making that more effective for projects that have 20 guitar tracks, all within 10 groups with two mono tracks each panned, it would make it more effective.

Not to mention good IR software are all designed to work with stereo input.. I wonder why that is..

**Comment by damiangr** [comment] 2023-04-15 09:02
> 

Most Amp simps ( like neural , ignite amps, amplitube can work on stereo track - yes but ams sim emulation will process mono input from L or R or mixed. They are not processing L and R independly. After AMP module yes - you have stereo processing with choruses , reversbs and so on.  Can you give me some examples with Stereo amp sims?

**Comment by jimc4893** [comment] 2023-04-15 09:05
Ok so I will explain further with more detail now that you are changing the argument so that you can win it. 

"Most amp modelers have a stereo option so you can bus two mono guitar tracks into it. This would be fantastic."

I am asking for MONO signals to be able to be sent into a STEREO plugin so that it can output STEREO audio from ONE amp.

Most IR software now such as GGD export their IRs as stereo by default, for all of the software that uses.. um... STEREO IR files.

**Comment by musicalentropy** [comment] 2023-04-19 08:29
I use the stereo processing option in my other amp sims all the time, so I'd like to say I would be interested too in an additional option allowing to have stereo processing. It's useful in a lot of different contexts, not only for mixing, but also because some people like me use stereo effect plug-ins before and after the plug-in. And it's a bit akward to have to use two instances with the same parameters to do the same thing. Moreover, plug-ins allow an option to be set which defines if the plug-in can be opened in your DAW either as a mono or a stereo plug-in, so I don't see why such an option should be a regression.

**Comment by BrunoDSL** [comment] 2023-04-19 12:32
> Most Amp simps ( like neural , ignite amps, amplitube can work on stereo track - yes but ams sim emulation will process mono input from L or R or mixed. They are not processing L and R independly. After AMP module yes - you have stereo processing with choruses , reversbs and so on. Can you give me some examples with Stereo amp sims?

Amplitube 5 has a parallel routing option which gives you two signals which are independent from each other. Helix Native also has that option. I believe Amplifkation 360 also does it, but I can't confirm it.

**Comment by musicalentropy** [comment] 2023-04-19 12:51
Amplifikation 360 has this option, TSE X50 too, same for Mercuriall amps, Nembrini, Neural DSP amp sims... By the way, Amplitube 5 has the worst workflow, as there is no direct way to use the same gear on left and right channels, you have to copy and paste gear + settings on each parallel path and it's very bad UX practice...

**Comment by jimc4893** [comment] 2023-04-19 15:45
> 

no point responding to the guy who didnt understand how clear this request was, as we all did. lol

**Comment by sdatkinson** [comment] 2023-04-19 18:40
Hey folks.

"Stereo" is tricky because there are at least 3 different things that people can be asking for.

I'll be breaking out this discussion out and we can address it piece by piece.

**Comment by jimc4893** [comment] 2023-04-19 20:20
> "Stereo" is tricky because there are at least 3 different things that people can be asking for.

thanks steven. we just want 2 inputs and 2 outputs out of NAM, where the existing functionality is just duplicated for both L and R inputs. i have an idea of how to implement it into the code with my understanding of iPlug2 but it just involves duplicating the signal onto both L and R. and if there is a mono signal, ignoring the stereo section.

**Comment by jimc4893** [comment] 2023-04-20 13:32
> C) Stops people asking for it, sometimes repeatedly.

i hear you, it'll shut me right up hah

**Comment by sdatkinson** [comment] 2023-05-01 04:39
Summing a stereo input is in with #166.

Dual mono is being tracked in #108, so I'm going to close this as a duplicate and we'll continue there.

**Closed by sdatkinson** 2023-05-01 04:39 UTC
Labels: enhancement, priority:low
