### ISSUE TITLE
Amps & IR's not loading / MacOS Sonoma 14.1.2  //  Logic Pro 10.8.1

### ISSUE THREAD

**Issue by CrashMitchell** [sdatkinson/NeuralAmpModelerPlugin#420] opened 2024-01-03 20:52 UTC
Setup - MacBook Pro M1 Max / MacOS Sonoma 14.1.2 // Logic Pro x 10.8.1

**Hi Steven,** 
How are you?

I'm running into a similar issue.

The stand alone app allows me to load Amps and IR's. 
Within Logic I can add the Plugin to a channel. I have control over the settings via the control knobs but I can't load any amps or IR's. I click the folder icon next the Amp symbol, access the folder located on my desktop and select the Vox30 V2.nam and it doesn't load. The same happens when attempting to load an IR. I  access the folder located on my desktop and select the Matchless 2x12 G12H30 sm57.wav and it doesn't load.

I used the **NeuralAmpModeler-v0.7.7-mac.dmg** installer.

I have also downloaded:
**NeuralAmpModeler.app.dSYM
NeuralAmpModeler.component.dSYM
NeuralAmpModeler.vst3.dSYM**
I haven't used these as I am unsure what to do with them and if I need to.

I would really appreciate some direction.

Many thanks

C

_Originally posted by @CrashMitchell in https://github.com/sdatkinson/NeuralAmpModelerPlugin/issues/414#issuecomment-1875748158_

**Comment by CrashMitchell** [comment] 2024-01-04 04:38
Hi Don, 
Thank you. I think I've tried that but will try again. 
Many thanks

C

**Comment by CrashMitchell** [comment] 2024-01-04 17:15
I have tried again.
When loading the standalone APP you do indeed select a folder and then can select from the content.
Although I get an input signal I still cant hear anything apart from the direct input from my Apogee Ensemble (Thunderbolt).

The Plugin situation is the same as before. I check in the Plugin manager and is has been recognised and loads ok. Within the Plugin you have to select the actual file and not the folder. I do that and still nothing loads. Very frustrating as the plugin looks and sounds fantastic from the clips I've been listening too. 

Any help is greatly appreciated. Thank you.

**Comment by sdatkinson** [comment] 2024-01-12 05:08
What is the complete path on your computer to the files you're trying to use?
Can you share copies of the files that aren't working?

**Comment by CrashMitchell** [comment] 2024-01-16 17:14
**Hi Steven,** 
Sorry for the delay in getting back to you. 

Example paths for Amp and IR is:

**AMP**
Desktop/Stuff/Studio7/Plugins/Neural Amp Model/Amp/Fender Twin Pack

*I can not up load the file as it will not allow me to add .nam extensions-
Tim R Fender TwinVerb Norm Bright.nam

**IR**
Desktop/Stuff/Studio7/Plugins/Neural Amp Model/IR/Celestion Greenback - Jet City Vertical 2 x 12IR

*I can not up load the file - 
Matchless 2x12 G12H30 sm57.wav

Is there any other way to upload the files to you?
The original Amp & IR were downloaded from ToneHunt.

Many thanks

**Comment by RRMRM** [comment] 2024-01-26 04:49
Hi Steven,

Just wanted to let you know that I am experiencing the same issue in Logic. It happened with Ventura and Sonoma. I have moved the file folders to a variety of locations with the same results. Interestingly enough, I have zero issues running the program in garageband. 

Thanks for the awesome app.

**Comment by Mickp69** [comment] 2024-02-26 13:11
Hi I have just installed v.0.7.8 and none of my .nam files or IR files from my previous version of NAM will load up as the files are greyed out in the folder I was previously using. Im using Sonoma on Mac v14.3

**Comment by vossenv** [comment] 2024-02-26 16:25
Hey @Mickp69 - try selecting the folder containing the files instead of the individual files (this is standalone?)

**Comment by Mickp69** [comment] 2024-02-26 18:19
Hi thanks for suggestion, it is standalone and I have picked the folder first but the trouble is files are greyed out in the folder and unavailable to select. The NAM plugin works just fine and loads all my .nam files in Logic Pro as I have just tried it out so not sure what the issue isSent from my iPhone 12 ProOn 26 Feb 2024, at 16:26, vossen ***@***.***> wrote:﻿
Hey @Mickp69 - try selecting the folder containing the files instead of the individual files (this is standalone?)

**Comment by sdatkinson** [comment] 2024-02-27 02:46
@Mickp69 you're having a separate problem from what this Issue is about.

You need to select the _folder_, not the _file_ in the macOS standalone. The reason is because macOS will not grant the standalone the permissions to the files that the arrows would access unless the user clicks with their mouse on the folder containing them in a picker dialog--hence the "odd one out" functionality.

Like this:


<img width="610" alt="image" src="https://github.com/sdatkinson/NeuralAmpModelerPlugin/assets/12240186/659a9dfa-aa8e-484d-bf9d-25f9c3fc7ef8">

Select the folder icon as usual...

<img width="789" alt="image" src="https://github.com/sdatkinson/NeuralAmpModelerPlugin/assets/12240186/6d4c0723-89a4-4952-8469-2556da05549b">

(_Single-_) click on the folder, then click "Open".

...and it'll open the first .nam in the folder.

---

I'm going to hide the comments about this separate issue as off-topic so I can keep this Issue focused on the OP's problem.

**Comment by Mickp69** [comment] 2024-02-27 10:43
Hi apologies as I hadn’t been using the standalone for a while and lost sight of the method. I use NAM mostly through Tonocracy and did have issues this week with Tonocracy plugin not validating in logic 10.8.1. but fine in my Motu DP.  This has now been fixed in Tonocracy 2.1 which the techs sent me a beta to try. Thanks again MickSent from my iPhone 12 ProOn 27 Feb 2024, at 02:47, Steven Atkinson ***@***.***> wrote:﻿
@Mickp69 you're having a separate problem from what this Issue is about.
You need to select the folder, not the file in the macOS standalone. The reason is because macOS will not grant the standalone the permissions to the files that the arrows would access unless the user clicks with their mouse on the folder containing them in a picker dialog--hence the "odd one out" functionality.
Like this:
image.png (view on web)
Select the folder icon as usual...
image.png (view on web)
(Single-) click on the folder, then click "Open".
...and it'll open the first .nam in the folder.

I'm going to hide the comments about this separate issue as off-topic so I can keep this Issue focused on the OP's problem.

**Comment by Roasteg** [comment] 2024-05-15 19:30
Experiencing the same issue. Running Sonoma 14.4.1, Reaper. Prompts me to open a file, not folder, then nothing happens when I choose file

**Comment by sdatkinson** [comment] 2024-06-01 22:30
I got an email notification for new activity on this Issue, but I don't see it.

Looking up at the above, it's a bit dizzying what this Issue is all about. If there's still a problem, please open a new Issue and we'll pick it up from there. Thanks!

**Closed by sdatkinson** 2024-06-01 22:30 UTC
Labels: bug, priority:low
