### ISSUE TITLE
[BUG] MacOS standalone app's Input Device is selected system default by default and none other works upon selection

### ISSUE THREAD

**Issue by piedpipr** [sdatkinson/NeuralAmpModelerPlugin#386] opened 2023-11-06 15:09 UTC
**Description**
The standalone app by default always uses *Default-Input* from the system setting, however, if I change it to my audio interface from the NAM app it stops. In an earlier version, it used to work upon exiting and re-opening but now the app does not remember the previously selected setting as a result it only takes input from system mic which is default.

**To Reproduce**
1. Open NAM Standalone on Mac
2. Go to "NeuralAmpModeler > Settings"
3. Change "Input Device"
4. See error, it stops working

**Expected behavior**
1. Either it will start taking input from selected source right away or
2. At least it will remember the last selected input source 

**Device**
 - OS - MacOS Ventura 13.6.1(intel)
 - Plugin version - 0.7.5
 - Standalone App

**Comment by 1BrentEdward** [comment] 2023-12-15 22:26
This is a huge issue for me too.  I should be able to select input 2 only.  (or 3, or whatever number of the inputs I have)

But it defaults to a stereo L&R input with input 1 assigned and unchangeable in the left input.

The standalone is unusable because of this. 

The fact that this has been going on and reported over and over and over again, with still no resolution is baffling.

**Comment by sdatkinson** [comment] 2023-12-19 07:12
Duplicate of #157

**Closed by sdatkinson** 2023-12-19 07:12 UTC
Labels: bug, priority:low, standalone
