### ISSUE TITLE
[BUG] Clicking noise on playback

### ISSUE THREAD

**Issue by hellobendaniel** [sdatkinson/NeuralAmpModelerPlugin#418] opened 2024-01-02 01:51 UTC
**Describe the bug**
When a .nam file is loaded in the NAM plugin, a clicking noise is generated on playback, regardless of playhead position.

**To Reproduce**
1. Load .nam file into plugin
2. Click play of recorded region
3. Listen to the sweet sounds of what i'd describe as 'predator clicks'

**Desktop (please complete the following information):**
 - macOS 14.2.1
 - Plugin version 0.7.7
 - AU
 - Logic Pro 10.7.8
 - 44.1 kHz
 - Buffer size 128, 256, 512 samples

**Comment by sdatkinson** [comment] 2024-01-02 02:26
Thanks for this!

I am not able to reproduce it on my side, but a possible explanation for this would be that there are samples that sometimes don't get written to during the resampling container's processing routine--see bullet 2 of https://github.com/iPlug2/iPlug2/issues/1038#issue-2044660490.

I believe that I've fixed this with PR #419, so if you're able to verify that that does it for you then we can call this closed.

**Comment by mattgoings** [comment] 2024-01-03 16:33
I can verify that PR #419 fixed the issue for me!

**Comment by sdatkinson** [comment] 2024-01-05 06:17
gonna close this as resolved!

**Closed by sdatkinson** 2024-01-05 06:17 UTC
Labels: bug, priority:low
