### ISSUE TITLE
[BUG] Standalone App only uses input 1 and 2, no matter the settings (macOS)

### ISSUE THREAD

**Issue by PrimalNerd** [sdatkinson/NeuralAmpModelerPlugin#314] opened 2023-06-30 20:15 UTC
If you want to set the input to something other than 1 or 2, the settings display that you changed the inputs, but the plugin continues to only listen to input 1 & 2.

macOS Ventura
Version 0.7.4
interface: Focusrite Scarlett 18i8 3rd gen

**Comment by sdatkinson** [comment] 2023-07-02 02:27
Unfortunately, this is a known bug. The root cause is upstream in iPlug2.

Closing as a duplicate of #157

**Closed by sdatkinson** 2023-07-02 02:27 UTC
Labels: bug, unread, priority:low
